version: "3.9"
services:

  api:
    build: 
      context: ./docker/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - todo-legal-net
    depends_on:
      - postgresql

  postgresql:
    build: 
      context: ./docker/database
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=todolegaldb
      - POSTGRES_USER=usertl
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - todo-legal-net
networks:
  todo-legal-net:
    name: todo-legal-net

volumes:
  postgres:
